### ISSUE TITLE
Fail on vuejs/vue UTF-8 encoding (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by edouard-lopez** [zats/github_bus_factor#2]
Project [vuejs/vue](https://github.com/vuejs/vue)

```
$ github_bus_factor vuejs/vue
1/6 Fetching repository info…
2/6 Fetching open PRs…
3/6 Fetching closed PRs…
/usr/lib/ruby/vendor_ruby/json/common.rb:223:in `encode': "\xE4" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)                                                                                             from /usr/lib/ruby/vendor_ruby/json/common.rb:223:in `generate'                                                                                                                                                    from /usr/lib/ruby/vendor_ruby/json/common.rb:223:in `generate'                                                                                                                                                    from /usr/lib/ruby/vendor_ruby/json/common.rb:394:in `dump'                                                                                                                                                        from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache/storage.rb:132:in `serialize_object'                                                                                                 from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache/storage.rb:128:in `block in serialize_entry'                                                                                         from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache/storage.rb:128:in `map'                                                                                                              from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache/storage.rb:128:in `serialize_entry'                                                                                                  from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache/storage.rb:46:in `write'                                                                                                             from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:279:in `store'                                                                                                                    from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:305:in `block in fetch'                                                                                                           from /var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'                                                                                                                            from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:303:in `fetch'                                                                                                                    from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:208:in `process'                                                                                                                  from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:146:in `call!'                                                                                                                    from /var/lib/gems/2.3.0/gems/faraday-http-cache-1.3.1/lib/faraday/http_cache.rb:119:in `call'                                                                                                                     from /var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'                                                                                                                    from /var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'                                                                                                                         from /var/lib/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'                                                                                                                                 from /var/lib/gems/2.3.0/gems/sawyer-0.7.0/lib/sawyer/agent.rb:94:in `call'
        from /var/lib/gems/2.3.0/gems/octokit-4.4.0/lib/octokit/connection.rb:154:in `request'
        from /var/lib/gems/2.3.0/gems/octokit-4.4.0/lib/octokit/connection.rb:84:in `paginate'
        from /var/lib/gems/2.3.0/gems/octokit-4.4.0/lib/octokit/client/pull_requests.rb:20:in `pull_requests'
        from /var/lib/gems/2.3.0/gems/github_bus_factor-0.1.9/lib/github_bus_factor.rb:152:in `block (2 levels) in <top (required)>'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:68:in `run!'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.3.0/gems/commander-4.4.0/lib/commander/import.rb:5:in `block in <top (required)>'
```

**Comment by oferzi23** [comment]
got the same error, anyone was able to fix this?

**Comment by iamareebjamal** [comment]
Ironic that bus factor of the repository itself got to it :stuck_out_tongue:
